# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"XLA_AVAILABLE": "00_core.ipynb",
         "XLAOptimProxy": "00_core.ipynb",
         "XLAOptCallback": "00_core.ipynb",
         "ChromeTrace": "01_utils.ipynb"}

modules = ["core.py"]

doc_url = "https://butchland.github.io/fastai_xla_extensions/"

git_url = "https://github.com/butchland/fastai_xla_extensions/tree/master/"

def custom_doc_links(name): return None
