# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02b_misc_utils.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai.optimizer import _BaseOptimizer
from fastcore.basics import patch

@patch
def __getstate__(self:_BaseOptimizer):
    "Pickling opt state should include `param_groups` and `defaults` "
    d = {
            'state': self.state_dict(),
            'param_groups': self.param_groups,
        }
    if hasattr(self,'defaults'):
        d['defaults'] = self.defaults
    return d

@patch
def __setstate__(self:_BaseOptimizer, data):
    "Pickling opt state should include `param_groups` and `defaults` "

    if 'defaults' in data:
        self.defaults = data['defaults']
    self.load_state_dict(data['state'])
    self.param_groups = data['param_groups']